In [1]:
import pandas as pd
import numpy as np
from itertools import permutations
from tqdm import tqdm

In [2]:
df = pd.read_csv("Day12_sample.txt", header=None,sep=' ')
df

                     0        1
0              ???.###    1,1,3
1       .??..??...?##.    1,1,3
2      ?#?#?#?#?#?#?#?  1,3,1,6
3        ????.#...#...    4,1,1
4  ????.######..#####.    1,6,5
5         ?###????????    3,2,1

In [3]:
df.iloc[:,0] =list(map(lambda x : list(x),df.iloc[:,0]))
df

                                                   0        1
0                              [?, ?, ?, ., #, #, #]    1,1,3
1         [., ?, ?, ., ., ?, ?, ., ., ., ?, #, #, .]    1,1,3
2      [?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?]  1,3,1,6
3            [?, ?, ?, ?, ., #, ., ., ., #, ., ., .]    4,1,1
4  [?, ?, ?, ?, ., #, #, #, #, #, #, ., ., #, #, ...    1,6,5
5               [?, #, #, #, ?, ?, ?, ?, ?, ?, ?, ?]    3,2,1

In [4]:
df.iloc[:,1] =list(map(lambda x : [int(x) for x in x.split(',')],df.iloc[:,1]))
df

                                                   0             1
0                              [?, ?, ?, ., #, #, #]     [1, 1, 3]
1         [., ?, ?, ., ., ?, ?, ., ., ., ?, #, #, .]     [1, 1, 3]
2      [?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?]  [1, 3, 1, 6]
3            [?, ?, ?, ?, ., #, ., ., ., #, ., ., .]     [4, 1, 1]
4  [?, ?, ?, ?, ., #, #, #, #, #, #, ., ., #, #, ...     [1, 6, 5]
5               [?, #, #, #, ?, ?, ?, ?, ?, ?, ?, ?]     [3, 2, 1]

In [5]:
# enlever tous les apostrophes
# Supprimer les apostrophes des chaînes de caractères
df[0] = df[0].apply(lambda x: [y.replace("'", "") for y in x])
df

                                                   0             1
0                              [?, ?, ?, ., #, #, #]     [1, 1, 3]
1         [., ?, ?, ., ., ?, ?, ., ., ., ?, #, #, .]     [1, 1, 3]
2      [?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?]  [1, 3, 1, 6]
3            [?, ?, ?, ?, ., #, ., ., ., #, ., ., .]     [4, 1, 1]
4  [?, ?, ?, ?, ., #, #, #, #, #, #, ., ., #, #, ...     [1, 6, 5]
5               [?, #, #, #, ?, ?, ?, ?, ?, ?, ?, ?]     [3, 2, 1]

In [6]:
# Créez une fonction pour enlever les points en doublon dans chaque liste
def remove_consecutive_dots(lst):
    result = []
    consecutive_dots = False

    for char in lst:
        if char == '.':
            if not consecutive_dots:
                result.append(char)
                consecutive_dots = True
        else:
            result.append(char)
            consecutive_dots = False

    return result

# Appliquez la fonction à la colonne
df[0] = df[0].apply(remove_consecutive_dots)

In [7]:
df

                                                   0             1
0                              [?, ?, ?, ., #, #, #]     [1, 1, 3]
1                  [., ?, ?, ., ?, ?, ., ?, #, #, .]     [1, 1, 3]
2      [?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?]  [1, 3, 1, 6]
3                        [?, ?, ?, ?, ., #, ., #, .]     [4, 1, 1]
4  [?, ?, ?, ?, ., #, #, #, #, #, #, ., #, #, #, ...     [1, 6, 5]
5               [?, #, #, #, ?, ?, ?, ?, ?, ?, ?, ?]     [3, 2, 1]

In [8]:
# Créez une fonction pour enlever les points à droite et à gauchede chaque liste
def remove_side_dots(lst):
    result = lst
    if result[0] == '.':
            result = result[1:]
    if lst[-1] == '.':
        result = result[:-1]

    return result

# Appliquez la fonction à la colonne
df[0] = df[0].apply(remove_side_dots)
df

                                                   0             1
0                              [?, ?, ?, ., #, #, #]     [1, 1, 3]
1                        [?, ?, ., ?, ?, ., ?, #, #]     [1, 1, 3]
2      [?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?, #, ?]  [1, 3, 1, 6]
3                           [?, ?, ?, ?, ., #, ., #]     [4, 1, 1]
4  [?, ?, ?, ?, ., #, #, #, #, #, #, ., #, #, #, ...     [1, 6, 5]
5               [?, #, #, #, ?, ?, ?, ?, ?, ?, ?, ?]     [3, 2, 1]

In [9]:
def make_réel(liste_line):

    # Map characters to binary representation
    binary_mapping_1 = {'?': 0, '.': 0, '#': 1}
    binary_mapping_2 = {'?': 0, '.': 1, '#': 0}
    binary_mapping_3 = {'?': 1, '.': 0, '#': 0}
    binary_list_1 = [binary_mapping_1[char] for char in liste_line]
    binary_list_2 = [binary_mapping_2[char] for char in liste_line]
    binary_list_3 = [binary_mapping_3[char] for char in liste_line]
    
    ##### Reshape the lists into a 2D NumPy array
    num_rows = 3
    num_cols = len(liste_line)
    numpy_array = np.array([binary_list_1,binary_list_2,binary_list_3]).reshape(num_rows, num_cols)
    return numpy_array

# ORIGINAL
def make_liste_arrangements(longueur, list_group):   

    # création de l'input lis
    input_list = list_group + ([0] * (longueur - sum(list_group)))
    
    # fonction pour supprimer les arrangements à groupes contigus
    def has_contiguous_positive_elements(arrangement):
        for i in range(len(arrangement) - 1):
            if arrangement[i] > 0 and arrangement[i + 1] > 0:
                return True
        return False
    
     # Utilisation de permutations pour obtenir tous les arrangements possibles 
    # sous forme de liste de tuples
    arrangements = permutations(input_list)
    
    # Filtrage des arrangements sans chiffres > 0 contigus et sans doublon
    # sous forme de liste de tuples
    
    filtered_arrangements = set([arrangement for arrangement in arrangements if not has_contiguous_positive_elements(arrangement)])
    
    # puis sous forme de liste de listes uniques
    filtered_arrangements = [list(sublist) for sublist in filtered_arrangements]
    
    # On instancie une liste d'arrangements vide
    liste_arrangements = []
    
    # Affichage des arrangements uniques avec des 1 et des 0
    for arrangement in filtered_arrangements:
        for i in range(len(arrangement)):
            if arrangement[i]>0:
                arrangement[i]=[1]*arrangement[i]
        arrangement = [item for sublist in arrangement for item in (sublist if isinstance(sublist, list) else [sublist])]
        liste_arrangements.append(arrangement)
    return(liste_arrangements)

# ORIGINAL REVU
def make_liste_arrangements(longueur, list_group):   

    # création de l'input lis
    input_list = list_group + ([0] * (longueur - sum(list_group)))
    
    def has_contiguous_positive_elements(arrangement):
        prev_nonzero = False
        for element in arrangement:
            if element > 0:
                if prev_nonzero:
                    return True
                prev_nonzero = True
            else:
                prev_nonzero = False
        return False
    
     # Utilisation de permutations pour obtenir tous les arrangements possibles 
    # sous forme de liste de tuples
    arrangements = permutations(input_list)
    
    # Filtrage des arrangements sans chiffres > 0 contigus et sans doublon
    # sous forme de liste de tuples
    
    filtered_arrangements = set([arrangement for arrangement in arrangements if not has_contiguous_positive_elements(arrangement)])
    
    # puis sous forme de liste de listes uniques
    filtered_arrangements = [list(sublist) for sublist in filtered_arrangements]
    
    # On instancie une liste d'arrangements vide
    liste_arrangements = []
    
    # Affichage des arrangements uniques avec des 1 et des 0
    for arrangement in filtered_arrangements:
        for i in range(len(arrangement)):         
            if arrangement[i]>0:
                arrangement[i]=["#"]*arrangement[i]
        arrangement = [item for sublist in arrangement for item in (sublist if isinstance(sublist, list) else [sublist])]
        liste_arrangements.append(arrangement)
    # Remplacement des 0 par des '.'
    liste_arrangements = [['.' if element == 0 else element for element in row] for row in liste_arrangements]

    return(liste_arrangements)

# ORIGINAL REVU REVU
def make_liste_arrangements(longueur, list_group):
    # create input list
    input_list = list_group + ([0] * (longueur - sum(list_group)))

    # check if an arrangement has contiguous positive elements
    def has_contiguous_positive_elements(arrangement):
        prev_nonzero = False
        for element in arrangement:
            if element > 0:
                if prev_nonzero:
                    return True
                prev_nonzero = True
            else:
                prev_nonzero = False
        return False

    # get unique arrangements without contiguous positive elements
    def get_unique_arrangements(arrangements):
        # Filtrage des arrangements sans chiffres > 0 contigus et sans doublon
        # sous forme de liste de tuples
        filtered_arrangements = set([arrangement for arrangement in arrangements if not has_contiguous_positive_elements(arrangement)])
        print(filtered_arrangements)
        # puis sous forme de liste de listes uniques           
        return [list(sublist) for sublist in filtered_arrangements]# if not has_contiguous_positive_elements(sublist)]


    # convert tuples to lists and replace 0s with .s
    def format_arrangements(arrangements):
        for arrangement in arrangements:
            arrangement = list(arrangement)
            for i in range(len(arrangement)):
                if arrangement[i] > 0:
                    arrangement[i] = ['#'] * arrangement[i]
            arrangement = [item for sublist in arrangement for item in (sublist if isinstance(sublist, list) else [sublist])]
            yield ['.' if element == 0 else element for element in arrangement]

    # get permutations and filter, format, and return
    #return list(format_arrangements(get_unique_arrangements(filtered_permutations)))
    return list(format_arrangements(get_unique_arrangements(permutations(input_list))))

In [10]:
#input_list = [1,1,2,2] + ([0] * (13 - sum([1,1,2,2])))

In [11]:
# ORIGINAL REVU REVU revu
def make_liste_arrangements(longueur, list_group):
    # create input list
    input_list = list_group + ([0] * (longueur - sum(list_group)))

    # check if an arrangement has contiguous positive elements
    def has_contiguous_positive_elements(arrangement):
        prev_nonzero = False
        for element in arrangement:
            if element > 0:
                if prev_nonzero:
                    return True
                prev_nonzero = True
            else:
                prev_nonzero = False
        return False

    # get unique arrangements without contiguous positive elements
    def get_unique_arrangements(arrangements):
        # Filtrage des arrangements sans chiffres > 0 contigus et sans doublon
        # sous forme de liste de tuples
        filtered_arrangements = set([arrangement for arrangement in arrangements if not has_contiguous_positive_elements(arrangement)])
        #print(filtered_arrangements)
        # puis sous forme de liste de listes uniques           
        return [list(sublist) for sublist in filtered_arrangements]# if not has_contiguous_positive_elements(sublist)]


    # convert tuples to lists and replace 0s with .s
    def format_arrangements(arrangements):
        for arrangement in arrangements:
            arrangement = list(arrangement)
            for i in range(len(arrangement)):
                if arrangement[i] > 0:
                    arrangement[i] = ['#'] * arrangement[i]
            arrangement = [item for sublist in arrangement for item in (sublist if isinstance(sublist, list) else [sublist])]
            yield ['.' if element == 0 else element for element in arrangement]

    def keep_only_ordered(permutations, list_group):
        for permutation in permutations:
            if [x for x in permutation if x > 0] == [x for x in list_group]:
                yield permutation       

    # get permutations and filter, format, and return
    #return list(format_arrangements(get_unique_arrangements(filtered_permutations)))
    return list(format_arrangements(get_unique_arrangements(keep_only_ordered(permutations(input_list), list_group))))

In [12]:
nb_argt = 0
for idx in tqdm(range(len(df))):
    réel = make_réel(df.iloc[idx,0])
    list_argt_line = make_liste_arrangements(len(df.iloc[idx,0]), df.iloc[idx,1])
    for argt in tqdm(list_argt_line) :    
        arrangement = make_réel(argt)
        #print((réel @ arrangement.T))
        if ((réel @ arrangement.T)[0,1] == 0) and ((réel @ arrangement.T)[1,0] == 0):
            nb_argt +=1
nb_argt

  0%|                                                                                            | 0/6 [00:00<?, ?it/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 500.69it/s]

100%|██████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]

100%|████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<?, ?it/s]
 50%|██████████████████████████████████████████                                          | 3/6 [00:00<00:00, 19.62it/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 250.02it/s]

100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 6168.09it/s]
 83%|██████████████████████████████████████████████████████████████████████              | 5/6 [00:00<00:00, 19.23it/s]
100%|███████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 34994.19it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  8.66it/s]

21

In [13]:
from itertools import permutations

def keep_only_ordered(permutations, list_group):
    for permutation in permutations:
        if [x for x in permutation if x > 0] == [x for x in list_group]:
            yield permutation

# La séquence de départ
input_list = [1, 3, 2, 0, 0, 0]

# La liste d'indices
list_group = [1, 3, 2]

# Utiliser un générateur pour économiser de la mémoire
filtered_permutations_generator = keep_only_ordered(permutations(input_list), list_group)

# Afficher les permutations filtrées
for perm in filtered_permutations_generator:
    print(perm)

(1, 3, 2, 0, 0, 0)
(1, 3, 2, 0, 0, 0)
(1, 3, 2, 0, 0, 0)
(1, 3, 2, 0, 0, 0)
(1, 3, 2, 0, 0, 0)
(1, 3, 2, 0, 0, 0)
(1, 3, 0, 2, 0, 0)
(1, 3, 0, 2, 0, 0)
(1, 3, 0, 0, 2, 0)
(1, 3, 0, 0, 0, 2)
(1, 3, 0, 0, 2, 0)
(1, 3, 0, 0, 0, 2)
(1, 3, 0, 2, 0, 0)
(1, 3, 0, 2, 0, 0)
(1, 3, 0, 0, 2, 0)
(1, 3, 0, 0, 0, 2)
(1, 3, 0, 0, 2, 0)
(1, 3, 0, 0, 0, 2)
(1, 3, 0, 2, 0, 0)
(1, 3, 0, 2, 0, 0)
(1, 3, 0, 0, 2, 0)
(1, 3, 0, 0, 0, 2)
(1, 3, 0, 0, 2, 0)
(1, 3, 0, 0, 0, 2)
(1, 0, 3, 2, 0, 0)
(1, 0, 3, 2, 0, 0)
(1, 0, 3, 0, 2, 0)
(1, 0, 3, 0, 0, 2)
(1, 0, 3, 0, 2, 0)
(1, 0, 3, 0, 0, 2)
(1, 0, 0, 3, 2, 0)
(1, 0, 0, 3, 0, 2)
(1, 0, 0, 0, 3, 2)
(1, 0, 0, 3, 2, 0)
(1, 0, 0, 3, 0, 2)
(1, 0, 0, 0, 3, 2)
(1, 0, 3, 2, 0, 0)
(1, 0, 3, 2, 0, 0)
(1, 0, 3, 0, 2, 0)
(1, 0, 3, 0, 0, 2)
(1, 0, 3, 0, 2, 0)
(1, 0, 3, 0, 0, 2)
(1, 0, 0, 3, 2, 0)
(1, 0, 0, 3, 0, 2)
(1, 0, 0, 0, 3, 2)
(1, 0, 0, 3, 2, 0)
(1, 0, 0, 3, 0, 2)
(1, 0, 0, 0, 3, 2)
(1, 0, 3, 2, 0, 0)
(1, 0, 3, 2, 0, 0)
(1, 0, 3, 0, 2, 0)
(1, 0, 3, 0, 0, 2)
(1, 0, 3, 0, 2, 0)
(1, 0, 3, 0, 0, 2)
(1, 0, 0, 3, 2, 0)
(1, 0, 0, 3, 0, 2)
(1, 0, 0, 0, 3, 2)
(1, 0, 0, 3, 2, 0)
(1, 0, 0, 3, 0, 2)
(1, 0, 0, 0, 3, 2)
(0, 1, 3, 2, 0, 0)
(0, 1, 3, 2, 0, 0)
(0, 1, 3, 0, 2, 0)
(0, 1, 3, 0, 0, 2)
(0, 1, 3, 0, 2, 0)
(0, 1, 3, 0, 0, 2)
(0, 1, 0, 3, 2, 0)
(0, 1, 0, 3, 0, 2)
(0, 1, 0, 0, 3, 2)
(0, 1, 0, 3, 2, 0)
(0, 1, 0, 3, 0, 2)
(0, 1, 0, 0, 3, 2)
(0, 0, 1, 3, 2, 0)
(0, 0, 1, 3, 0, 2)
(0, 0, 1, 0, 3, 2)
(0, 0, 0, 1, 3, 2)
(0, 0, 1, 3, 2, 0)
(0, 0, 1, 3, 0, 2)
(0, 0, 1, 0, 3, 2)
(0, 0, 0, 1, 3, 2)
(0, 1, 3, 2, 0, 0)
(0, 1, 3, 2, 0, 0)
(0, 1, 3, 0, 2, 0)
(0, 1, 3, 0, 0, 2)
(0, 1, 3, 0, 2, 0)
(0, 1, 3, 0, 0, 2)
(0, 1, 0, 3, 2, 0)
(0, 1, 0, 3, 0, 2)
(0, 1, 0, 0, 3, 2)
(0, 1, 0, 3, 2, 0)
(0, 1, 0, 3, 0, 2)
(0, 1, 0, 0, 3, 2)
(0, 0, 1, 3, 2, 0)
(0, 0, 1, 3, 0, 2)
(0, 0, 1, 0, 3, 2)
(0, 0, 0, 1, 3, 2)
(0, 0, 1, 3, 2, 0)
(0, 0, 1, 3, 0, 2)
(0, 0, 1, 0, 3, 2)
(0, 0, 0, 1, 3, 2)
(0, 1, 3, 2, 0, 0)
(0, 1, 3, 2, 0, 0)
(0, 1, 3, 0, 2, 0)
(0, 1, 3, 0, 0, 2)
(0, 1, 3, 0, 2, 0)
(0, 1, 3, 0, 0, 2)
(0, 1, 0, 3, 2, 0)
(0, 1, 0, 3, 0, 2)
(0, 1, 0, 0, 3, 2)
(0, 1, 0, 3, 2, 0)
(0, 1, 0, 3, 0, 2)
(0, 1, 0, 0, 3, 2)
(0, 0, 1, 3, 2, 0)
(0, 0, 1, 3, 0, 2)
(0, 0, 1, 0, 3, 2)
(0, 0, 0, 1, 3, 2)
(0, 0, 1, 3, 2, 0)
(0, 0, 1, 3, 0, 2)
(0, 0, 1, 0, 3, 2)
(0, 0, 0, 1, 3, 2)